const puppeteer = require('puppeteer');

exports.handler = async (event, context) => {
  const headers = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Allow-Methods': 'POST, OPTIONS'
  };

  if (event.httpMethod === 'OPTIONS') {
    return {
      statusCode: 200,
      headers,
      body: ''
    };
  }

  try {
    const { content, userData, docTitle } = JSON.parse(event.body);
    
    if (!content) {
      return {
        statusCode: 400,
        headers,
        body: JSON.stringify({ error: 'Missing content' })
      };
    }

    // Create HTML with header and footer
    const htmlContent = createPDFHTML(content, userData, docTitle);
    
    // Generate PDF
    const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
    
    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
    
    const pdf = await page.pdf({
      format: 'A4',
      margin: {
        top: '1in',
        bottom: '1in',
        left: '1in',
        right: '1in'
      },
      printBackground: true
    });
    
    await browser.close();
    
    return {
      statusCode: 200,
      headers: {
        ...headers,
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${docTitle || 'document'}.pdf"`
      },
      body: pdf.toString('base64'),
      isBase64Encoded: true
    };

  } catch (error) {
    console.error('PDF generation error:', error);
    return {
      statusCode: 500,
      headers,
      body: JSON.stringify({ error: 'Failed to generate PDF' })
    };
  }
};

function createPDFHTML(content, userData, docTitle) {
  const headerInfo = userData && userData.userName ? 
    `Claim Navigator — Confidential Claim File<br>
     Policyholder: ${userData.userName} | Policy #: ${userData.policyNumber || '[Policy Number]'} | Claim #: ${userData.claimNumber || '[Claim Number]'}<br>
     Date of Loss: ${userData.dateOfLoss || '[Date of Loss]'} | Property: ${userData.propertyAddress || '[Property Address]'}` :
    'Demo Document – Header Info Not Available';

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <style>
        @page {
          margin: 1in;
          @top-center {
            content: "Claim Navigator — Confidential Claim File";
            font-family: Helvetica, Arial, sans-serif;
            font-size: 9pt;
            color: #666;
          }
          @bottom-center {
            content: "© Claim Navigator — Confidential · Generated by Claim Navigator";
            font-family: Helvetica, Arial, sans-serif;
            font-size: 8pt;
            color: #999;
            opacity: 0.3;
          }
        }
        
        body {
          font-family: 'Inter', Arial, sans-serif;
          line-height: 1.6;
          color: #111827;
          margin: 0;
          padding: 0;
        }
        
        .header {
          background: #f8fafc;
          border: 1px solid #e5e7eb;
          padding: 15px;
          margin-bottom: 30px;
          border-radius: 8px;
          font-size: 9pt;
          color: #666;
          text-align: center;
        }
        
        .content {
          line-height: 1.8;
          margin-bottom: 30px;
        }
        
        .footer {
          position: fixed;
          bottom: 20px;
          left: 50%;
          transform: translateX(-50%);
          font-size: 8pt;
          color: #999;
          opacity: 0.3;
          text-align: center;
        }
        
        h1, h2, h3 {
          color: #1e40af;
        }
        
        .document-title {
          text-align: center;
          font-size: 18pt;
          font-weight: bold;
          margin-bottom: 20px;
          color: #1e40af;
        }
      </style>
    </head>
    <body>
      <div class="header">
        ${headerInfo}
      </div>
      
      <div class="content">
        ${content}
      </div>
      
      <div class="footer">
        © Claim Navigator — Confidential · Generated by Claim Navigator
      </div>
    </body>
    </html>
  `;
}